services:
  ninja_chat_server:
    image: ghcr.io/coderdojonijmegen/ninja-chat:latest
    container_name: ninja_chat_server
    pull_policy: always
    user: "node"
    environment:
      - NODE_ENV=production
    networks:
      - proxy

networks:
  proxy:
    external: true
